[package]
name = "verifier2"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-groth16 = "1.0.5"
risc0-zkvm = { version = "1.0.5" }
risc0-zkp = { version = "1.0.5" }
bincode = "1.3"
hex = "0.4"
